arb-dir: lib/l10n # đường dẫn đến folder "l10n"
template-arb-file: app_en.arb #
output-localization-file: app_localizations.dart # tên file khi build ra
output-class: SAppLanguages	# tên class trong file "app_localizations.dart"

