name: strava
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  # utils
  flutter_dotenv: ^6.0.0
  connectivity_plus: ^6.1.4
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  modal_bottom_sheet: ^3.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  easy_debounce: ^2.0.3
  flutter_svg: ^2.2.0

  # local storage
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path: ^1.9.1
  
  # router
  go_router: ^16.1.0

  # Icons
  iconsax_flutter: ^1.0.1
  cupertino_icons: ^1.0.2

  # State Management
  flutter_riverpod: ^2.6.1

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.2

  # google map
  google_maps_flutter: ^2.12.3
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # State Management
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  generate: true

  # --------------------- assets ---------------------- #

  # fonts
  fonts:
    - family: Be Vietnam Pro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-Italic.ttf
          style: italic
  
  assets:
    # images
    - assets/imgs/
    - assets/imgs/logos/
    - assets/imgs/onboardings/

    # icons
    - assets/icons/

    # env
    - lib/envs/

    # google map styles
    - assets/map_styles/