// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo1Jakq8CCq3ojvZEFgX4VBgahEMU4iYY',
    appId: '1:542258239895:web:e4cc73f50f236aa58f8cd2',
    messagingSenderId: '542258239895',
    projectId: 'strava-ac375',
    authDomain: 'strava-ac375.firebaseapp.com',
    storageBucket: 'strava-ac375.firebasestorage.app',
    measurementId: 'G-1M1VR5PSVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOVGqHruZYO1da_e9YyToYysJv831FuG0',
    appId: '1:542258239895:android:5bbda6a821c8ade48f8cd2',
    messagingSenderId: '542258239895',
    projectId: 'strava-ac375',
    storageBucket: 'strava-ac375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3XsknaSCdzemRmhO5OYfgPEbAErBS9wQ',
    appId: '1:542258239895:ios:c2fd077a5af2ffee8f8cd2',
    messagingSenderId: '542258239895',
    projectId: 'strava-ac375',
    storageBucket: 'strava-ac375.firebasestorage.app',
    iosBundleId: 'com.example.strava',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3XsknaSCdzemRmhO5OYfgPEbAErBS9wQ',
    appId: '1:542258239895:ios:c2fd077a5af2ffee8f8cd2',
    messagingSenderId: '542258239895',
    projectId: 'strava-ac375',
    storageBucket: 'strava-ac375.firebasestorage.app',
    iosBundleId: 'com.example.strava',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo1Jakq8CCq3ojvZEFgX4VBgahEMU4iYY',
    appId: '1:542258239895:web:eecaaebcce4c9a288f8cd2',
    messagingSenderId: '542258239895',
    projectId: 'strava-ac375',
    authDomain: 'strava-ac375.firebaseapp.com',
    storageBucket: 'strava-ac375.firebasestorage.app',
    measurementId: 'G-WC2ERGFKKH',
  );
}
